name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - test
      - main

env:
  IMAGE_REPOSITORY: gdtcecbackend
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  Build-Image:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set container registry based on branch
      id: registry
      run: |
        if [ "${GITHUB_REF##*/}" = "main" ]; then
          echo "CONTAINER_REGISTRY=cecacrappprod01.azurecr.io" >> $GITHUB_ENV
        else
          echo "CONTAINER_REGISTRY=cecacrapptest01.azurecr.io" >> $GITHUB_ENV
        fi

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Get short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-4)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.SHORT_SHA }}
